// Auto-generated by @vreinai/faststore-components setup
// Re-exports FastStore's useQuery with a semantic name for Vrein components.
// If FastStore restructures its SDK exports, update this file only — no component changes needed.
// @ts-ignore — FastStore internal module, resolved at build time via tsconfig baseUrl
export { useQuery as vreinQueryExecutor } from 'src/sdk/graphql/useQuery'
