// Auto-generated by @vreinai/faststore-components setup
// Re-exports Vrein GraphQL resolvers from the package for registration in FastStore's thirdParty resolver index.
// IMPORTANT: must import from the '/graphql' subpath. The root export pulls in
// @faststore/sdk (ESM-only), which crashes when loaded by Node outside the bundler.
export { vreinResolvers as default } from '@vreinai/faststore-components/graphql'
