// Auto-generated by @vreinai/faststore-components setup
// Re-exports Vrein GraphQL resolvers from the package for registration in FastStore's thirdParty resolver index.
export { vreinResolvers as default } from '@vreinai/faststore-components'
