// Auto-generated by @vreinai/faststore-components setup
// These gql() calls are scanned by FastStore codegen and produce typed hooks + persisted query hashes.
// DO NOT import these documents directly in components — import from @generated/graphql after yarn build.
// @ts-ignore — gql is re-exported by codegen; @generated/graphql is available after build
import { gql } from '@generated/graphql'

// @ts-ignore
export const VreinProductsQueryDocument = gql`
  query VreinProductsQuery($sectionId: String!, $context: String) {
    vreinProducts(sectionId: $sectionId, context: $context) {
      products {
        id
        sku
        slug
        name
        brand {
          name
        }
        image {
          url
          alternateName
        }
        offers {
          offers {
            price
            listPrice
            availability
          }
        }
        isVariantOf {
          productGroupID
          name
        }
      }
      totalCount
      title
      endpointName
      apiUrl
    }
  }
`

// @ts-ignore
export const VreinImagesQueryDocument = gql`
  query VreinImagesQuery(
    $sectionId: String!
    $email: String
    $categoryId: String
    $whitelabel: String
    $sessionGuid: String
  ) {
    vreinImages(
      sectionId: $sectionId
      email: $email
      categoryId: $categoryId
      whitelabel: $whitelabel
      sessionGuid: $sessionGuid
    ) {
      images {
        title
        image
        mobileImage
        link
      }
      smartCountdown {
        dateStart
        dateEnd
        fontSizeDesktop
        fontSizeMobile
        positionDesktop
        positionMobile
        fontColor
        enabled
        timeZoneOffset
      }
    }
  }
`

// @ts-ignore
export const VreinProductDataQueryDocument = gql`
  query VreinProductDataQuery($productId: String, $skuId: String) {
    vreinProductData(productId: $productId, skuId: $skuId) {
      id
      sku
      slug
      name
      description
      brand
      categories
      categoryIds
      categoryNames
      price
      listPrice
      availability
      image
      url
    }
  }
`

// @ts-ignore
export const VreinCategoryIdQueryDocument = gql`
  query VreinCategoryIdQuery($pathname: String!) {
    vreinCategoryId(pathname: $pathname) {
      categoryId
    }
  }
`
