'use client'

/**
 * VreinPopup — wrapper FastStore
 * Auto-generated by @vreinai/faststore-components setup
 *
 * Sección CMS que resuelve un popup (modal) o slider de recomendaciones
 * BrainDW/Vrein según la página actual. Colocar en el Global Section del CMS
 * para que se resuelva en todas las páginas. Toda la lógica de resolución de
 * sección, gating SSR-safe, y almacenamiento (ShowOnce / colapso del slider)
 * vive en el paquete NPM — este archivo solo inyecta las dependencias de
 * FastStore (cart, query executor, documento persistido).
 *
 * Este es el ÚNICO archivo que necesita importaciones específicas de FastStore
 * para esta sección.
 */

import { VreinPopup as VreinPopupBase } from '@vreinai/faststore-components'

// @ts-ignore — FastStore internal: cart state (parity with VreinCarouselProps.cartId)
import { useCart } from 'src/sdk/cart'
// Vrein persisted-query adapter: isolated import so only this file needs updating if FastStore moves useQuery
// @ts-ignore
import { vreinQueryExecutor } from 'src/customizations/src/sdk/vreinQueryAdapter'
// @ts-ignore — generated by codegen after `yarn build`; available at build time via @generated/graphql
import { VreinPopupQueryDocument } from '@generated/graphql'

export function VreinPopup() {
  const { id: cartId } = useCart()

  return (
    <VreinPopupBase
      useQueryFn={vreinQueryExecutor}
      vreinPopupDocument={VreinPopupQueryDocument}
      cartId={cartId}
    />
  )
}

export default VreinPopup
