'use client'

/**
 * VreinCarousel — wrapper FastStore
 * Auto-generated by @vreinai/faststore-components setup
 *
 * Este archivo es el ÚNICO que necesita importaciones específicas de FastStore.
 * Toda la lógica de rendering, métricas y context está en el paquete NPM.
 */

import React, { useEffect, useMemo, useState } from 'react'
import { VreinCarousel as VreinCarouselBase } from '@vreinai/faststore-components'
import type { VreinCarouselProps } from '@vreinai/faststore-components'

// @ts-ignore — FastStore internal: cart state
import { useCart } from 'src/sdk/cart'
// @ts-ignore — FastStore SDK: search state (URL-driven, no additional fetch)
import { useSearch } from '@faststore/sdk'
// @ts-ignore — FastStore: SWR-cached gallery query (shares cache with SearchWrapper)
import { useQuery } from 'src/sdk/graphql/useQuery'
// @ts-ignore — FastStore: localized variables for gallery query
import { query as productGalleryQuery } from 'src/sdk/product/useProductGalleryQuery'
// Vrein persisted-query adapter: isolated import so only this file needs updating if FastStore moves useQuery
// @ts-ignore
import { vreinQueryExecutor } from 'src/customizations/src/sdk/vreinQueryAdapter'
// @ts-ignore — generated by codegen after `yarn build`; available at build time via @generated/graphql
import { VreinProductsQueryDocument } from '@generated/graphql'
// @ts-ignore
import { useLocalizedVariables } from 'src/sdk/product/useLocalizedVariables'
// @ts-ignore — Override system from FastStore
import { getSectionOverrides } from 'src/sdk/overrides/overrides'
// @ts-ignore
import { ProductShelfDefaultComponents } from 'src/components/sections/ProductShelf/DefaultComponents'
// @ts-ignore
import { override as productShelfOverride } from 'src/customizations/src/components/overrides/ProductShelf'

function resolveProductCardOverride() {
  try {
    const hasExplicitOverride =
      (productShelfOverride as any)?.components?.__experimentalProductCard != null

    if (!hasExplicitOverride) return null

    const overrides = getSectionOverrides(
      ProductShelfDefaultComponents,
      { ...productShelfOverride, section: 'ProductShelf' } as any
    ) as any

    const resolved = overrides?.__experimentalProductCard
    return resolved?.Component ? resolved : null
  } catch {
    return null
  }
}

const ResolvedProductCard = resolveProductCardOverride()

export const VreinCarousel = ({ sectionId }: Pick<VreinCarouselProps, 'sectionId'>) => {
  const upper = sectionId.toUpperCase()
  const isSnrSection = upper.includes('-SNR-') || upper.includes('SEARCHNORESULT')
  const isSrSection = upper.includes('-SR-') || (upper.includes('-SEARCH-') && !isSnrSection)

  const [isOnSearchPage] = useState(() => {
    if (typeof window === 'undefined') return false
    return window.location.pathname === '/s' && new URLSearchParams(window.location.search).has('q')
  })

  const needsSearchCheck = isOnSearchPage && (isSnrSection || isSrSection)

  const { state: searchState, itemsPerPage: searchItemsPerPage } = useSearch()

  const searchVars = useLocalizedVariables({
    first: searchItemsPerPage,
    after: '0',
    sort: searchState.sort,
    term: searchState.term ?? '',
    selectedFacets: searchState.selectedFacets,
  })

  const { data: galleryData, isValidating: galleryLoading } = useQuery(
    productGalleryQuery,
    searchVars,
    { doNotRun: !needsSearchCheck }
  )

  const hasSearchResults = useMemo<boolean | null | undefined>(() => {
    if (!needsSearchCheck) return undefined
    if (galleryLoading || galleryData === undefined) return null
    const totalCount = (galleryData as any)?.search?.products?.pageInfo?.totalCount ?? 0
    return totalCount > 0
  }, [needsSearchCheck, galleryLoading, galleryData])

  const pageTypeOverride = isOnSearchPage
    ? (isSnrSection ? 'searchnoresult' : isSrSection ? 'search' : undefined)
    : undefined

  const { id: cartId } = useCart()

  useEffect(() => {
    if (cartId) {
      localStorage.setItem('bdw_cart_id', cartId)
    }
  }, [cartId])

  return (
    <VreinCarouselBase
      sectionId={sectionId}
      cartId={cartId}
      hasSearchResults={hasSearchResults}
      pageTypeOverride={pageTypeOverride as any}
      productCardOverride={ResolvedProductCard}
      useQueryFn={vreinQueryExecutor}
      vreinProductsDocument={VreinProductsQueryDocument}
    />
  )
}

export default VreinCarousel
