'use client'

/**
 * VreinImageBanner — wrapper FastStore
 * Auto-generated by @vreinai/faststore-components setup
 *
 * Toda la lógica de rendering y métricas está en el paquete NPM.
 * Este wrapper solo obtiene el cartId de FastStore para las métricas.
 */

import React from 'react'
import { VreinImageBanner as VreinImageBannerBase } from '@vreinai/faststore-components'
import type { VreinImageBannerProps } from '@vreinai/faststore-components'

// @ts-ignore — FastStore internal: cart state
import { useCart } from 'src/sdk/cart'
// Vrein persisted-query adapter: isolated import so only this file needs updating if FastStore moves useQuery
// @ts-ignore
import { vreinQueryExecutor } from 'src/customizations/src/sdk/vreinQueryAdapter'
// @ts-ignore — generated by codegen after `yarn build`; available at build time via @generated/graphql
import { VreinImagesQueryDocument } from '@generated/graphql'

export const VreinImageBanner = ({
  sectionId,
  height,
  showLazyLoading,
  lazyLoadingHeight,
}: Pick<VreinImageBannerProps, 'sectionId' | 'height' | 'showLazyLoading' | 'lazyLoadingHeight'>) => {
  const { id: cartId } = useCart()

  return (
    <VreinImageBannerBase
      sectionId={sectionId}
      cartId={cartId}
      height={height}
      showLazyLoading={showLazyLoading}
      lazyLoadingHeight={lazyLoadingHeight}
      useQueryFn={vreinQueryExecutor}
      vreinImagesDocument={VreinImagesQueryDocument}
    />
  )
}

export default VreinImageBanner
