'use client'

/**
 * VreinTracking — wrapper FastStore
 * Auto-generated by @vreinai/faststore-components setup
 *
 * Sección CMS que carga el script de tracking BrainDW/Vrein desde el CDN.
 * Colocar en el Global Section del CMS para que cargue en todas las páginas.
 * Toda la lógica (carga del script, captura de eventos via useAnalyticsEvent,
 * buffer y forwarding a __VREIN_PROCESS_EVENT) vive en el paquete NPM.
 */

import { VreinTracking } from '@vreinai/faststore-components'

export { VreinTracking }
export default VreinTracking
